### ISSUE TITLE
Using the ansible playbook sans terraform?

### ISSUE THREAD

**Issue by astewart-twist** [nautsio/ducp-terraform-ansible#2]
Thanks for putting this together.  Can the ansible playbook be used standalone (say with a couple in-house VMWare VMs) ?  Any potential caveats for a non-ansible-expert?

**Comment by superseb** [comment]
Hi @astewart-twist ,

Sure. Currently we use terraform.py to load the inventory from the tfstate file of Terraform. You can easily replace this with your own inventory (file/binary). The matching is currently done on resource name (ducp-controller and ducp-replica*), so you might have to adjust those. The roles are generic. If you can give me more details on your setup I can help you make it work. 

Btw, Terraform also has a vSphere and vCloud Director provider, so if you are using one of those, we can add support for it.

**Comment by superseb** [comment]
Do you need any help with this @astewart-twist ?

**Comment by superseb** [comment]
Open a new issue if you want some help!
