### ISSUE TITLE
nat_ip does not resolve anymore since Terraform 0.6.11

### ISSUE THREAD

**Issue by superseb** [nautsio/ducp-terraform-ansible#3]
Terraform.py uses nat_ip to retrieve instance IP, as of Terraform 0.6.11 this resolves to assigned_nat_ip (https://github.com/hashicorp/terraform/issues/4896)

Waiting for response from HashiCorp to file an issue for terraform.py to adjust this or if HashiCorp will fix it.

**Comment by ryane** [comment]
fyi, this was addressed in https://github.com/CiscoCloud/terraform.py/pull/26

**Comment by superseb** [comment]
Awesome, thanks for the notification
